version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      #- TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-label-sandisk/jellyfin/library:/config
      - /srv/dev-disk-by-label-sandisk/jellyfin/tvseries:/data/tvshows
      - /srv/dev-disk-by-label-sandisk/jellyfin/movies:/data/movies
      #- /path for transcoding:/transcode #optional
      #- /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      #- 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
      #- /dev/vchiq:/dev/vchiq #optional
    restart: unless-stopped
