version: "2"

services:
  kodexplorer:
    image: ugeek/kodexplorer:arm
    restart: "always"
    container_name: kodexplorer
    ports:
      - 8081:80
    volumes:
      - /srv/dev-disk-by-label-sandisk/kod:/var/www/html
