version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      #- TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      #- /path/to/appdata/config:/config
      - /srv/dev-disk-by-label-sandisk/downloads:/downloads
    ports:
      - 7881:7881
      - 7881:7881/udp
      - 8080:8080
    restart: unless-stopped
